/* Hamburg Keşif — içerik.
   Bölgeler XP ile sırayla açılır. Görev tipleri: gez (gör), ye (yemek/içmek), yap (aktivite).
   ph = [Almanca cümle, Türkçesi]; chef = aşçı notu; pork = domuz uyarısı; film = vlog çekim fikri.
   tags: free (ücretsiz), rain (yağmurda olur), night (akşam/gece), view (manzara), fisch, franz, klasik, ferry, market, museum */

const REGIONS=[
  {id:"altstadt",n:"Altstadt & Neustadt",de:"Innenstadt",xp:0,c:"#d1343b",ll:[53.5520,9.9900],z:15,
   d:"Şehrin kalbi: Rathaus, Alster kuğuları, 1842 yangınından kalan sokaklar. Her şey yürüme mesafesinde."},
  {id:"speicher",n:"Speicherstadt & HafenCity",de:"Speicherstadt",xp:0,c:"#b5562a",ll:[53.5425,9.9930],z:15,
   d:"Kırmızı tuğla depolar, kanallar ve Elbphilharmonie. UNESCO Dünya Mirası."},
  {id:"hafen",n:"Landungsbrücken & Liman",de:"Hafen",xp:80,c:"#1f6fb2",ll:[53.5460,9.9740],z:15,
   d:"Fischbrötchen, feribotlar, Michel. Hamburg'un 'Avrupa'nın kapısı' olduğunu burada hissedersin."},
  {id:"stpauli",n:"St. Pauli & Reeperbahn",de:"Kiez",xp:180,c:"#7a3fb0",ll:[53.5500,9.9620],z:15,
   d:"Kiez: Beatles, futbol, gece hayatı ve Pazar sabahı Fischmarkt."},
  {id:"stgeorg",n:"St. Georg & Hauptbahnhof",de:"St. Georg",xp:280,c:"#c0398a",ll:[53.5545,10.0100],z:15,
   d:"Garın arkası: Lange Reihe kafeleri, Steindamm'da sıla kokusu, müzeler."},
  {id:"schanze",n:"Sternschanze & Karoviertel",de:"Schanze",xp:400,c:"#2b9a66",ll:[53.5610,9.9660],z:15,
   d:"Alternatif Hamburg: Rote Flora, kahve kavurucuları, Tim Mälzer'in mutfağı."},
  {id:"altona",n:"Altona & Ottensen",de:"Altona",xp:520,c:"#d4881c",ll:[53.5490,9.9330],z:15,
   d:"Eskiden ayrı bir Danimarka şehriydi. Balıkçı limanı, Altonaer Balkon ve Ottensen'in dar sokakları."},
  {id:"elbstrand",n:"Elbstrand: Övelgönne → Blankenese",de:"Elbstrand",xp:650,c:"#d6a51c",ll:[53.5530,9.8600],z:13,
   d:"Kumsal, dev konteyner gemileri ve kaptan evleriyle dolu merdivenli tepeler."},
  {id:"alster",n:"Außenalster, Winterhude & Stadtpark",de:"Alster",xp:800,c:"#2a8fb5",ll:[53.5750,10.0150],z:14,
   d:"Hamburglular hafta sonunu burada geçirir: kano, koşu, park, planetaryum."},
  {id:"eimsbuettel",n:"Eimsbüttel, Eppendorf & Hoheluft",de:"Eimsbüttel",xp:950,c:"#5a7d2a",ll:[53.5780,9.9650],z:14,
   d:"Mahalle hayatı: Avrupa'nın en uzun pazarlarından biri, en iyi Franzbrötchen, Hagenbeck."},
  {id:"elbinseln",n:"Elbinseln: Wilhelmsburg & Veddel",de:"Elbinseln",xp:1100,c:"#3d4fb8",ll:[53.5050,10.0050],z:13,
   d:"Elbe'nin adaları: göç müzesi, savaş bunkerinden enerji santrali, işçi lokantaları."},
  {id:"altesland",n:"Finkenwerder & Altes Land",de:"Altes Land",xp:1250,c:"#8a9a1c",ll:[53.5350,9.7900],z:12,
   d:"Kuzey Avrupa'nın en büyük meyve bahçesi bölgesi ve meşhur Finkenwerder pisi balığı."},
  {id:"ausflug",n:"Günübirlik Kaçamaklar",de:"Tagesausflüge",xp:1400,c:"#6d5a4a",ll:[53.7000,9.9000],z:8,
   d:"Deutschlandticket (aylık 63 €) ile bölgesel trenlerle: Lübeck, Lüneburg, Kuzey Denizi, Sylt…"}
];

const QUESTS=[
/* ---------------- ALTSTADT & NEUSTADT ---------------- */
{id:"rathaus",r:"altstadt",t:"gez",n:"Rathaus",xp:20,ll:[53.5507,9.9926],tags:["free","rain"],
 why:"647 odalı neo-rönesans belediye sarayı (1897). Hamburg hâlâ bir 'şehir-devlet' — eyalet meclisi de burada toplanır.",
 tip:"Giriş holüne girmek ücretsiz. Arka avludaki Hygieia çeşmesine bak (1892 kolera salgınının anısına). İçerisi kısa rehberli turla geziliyor.",
 ph:["Wo ist der Eingang?","Giriş nerede?"],film:"Rathausmarkt'ın ortasından yavaş bir yukarı tilt: kule 112 m."},
{id:"jungfernstieg",r:"altstadt",t:"gez",n:"Jungfernstieg & Alsterarkaden",xp:20,ll:[53.5520,9.9922],tags:["free"],
 why:"Hamburg'un vitrini. Alster kuğuları şehre aittir; bir 'Schwanenvater' (kuğu babası) onlara bakar ve kışın kışlığa taşır.",
 tip:"Alsterarkaden'in beyaz kemerleri altından Rathausschleuse'ye yürü. Yazın Binnenalster'de 60 m'lik fıskiye çalışır.",
 ph:["Moin!","Merhaba! (Hamburg'da günün her saati kullanılır, 'Moin moin' demek gevezelik sayılır 😄)"],film:"Kemerlerin arasından Alster'e doğru yürüyen bir tracking shot."},
{id:"nikolai",r:"altstadt",t:"gez",n:"Mahnmal St. Nikolai",xp:30,ll:[53.5475,9.9906],tags:["view","rain","museum"],
 why:"1943 'Gomorrha' bombardımanında yıkılan kilisenin ayakta kalan kulesi; bugün savaş anıtı.",
 tip:"Asansörle 76 m'ye çık — Speicherstadt ve liman tam ayağının altında. Bodrumdaki küçük müze çok etkileyici.",
 ph:["Eine Karte, bitte.","Bir bilet, lütfen."]},
{id:"chilehaus",r:"altstadt",t:"gez",n:"Chilehaus & Kontorhausviertel",xp:20,ll:[53.5482,10.0014],tags:["free"],
 why:"1924'te bitti; gemi pruvasına benzeyen köşesiyle tuğla ekspresyonizminin simgesi. Speicherstadt ile birlikte UNESCO Dünya Mirası.",
 tip:"Pumpenstraße ile Messberg köşesinde dur — 'pruva' en iyi buradan görünür.",
 ph:["Wie alt ist das Gebäude?","Bu bina kaç yaşında?"],film:"Köşeden aşağıdan yukarı geniş açı: bina gerçekten gemi gibi duruyor."},
{id:"petri",r:"altstadt",t:"gez",n:"St. Petri Kulesi",xp:30,ll:[53.5505,9.9965],tags:["view"],
 why:"Hamburg'un en eski kilisesi. 544 basamak tırmanıp şehri yukarıdan görürsün — ücreti sembolik.",
 tip:"Kalabalık sevmiyorsan Michel yerine burası. Kulenin üst pencerelerinden Alster ve Mönckebergstraße birlikte görünür.",
 ph:["Wie viele Stufen sind das?","Kaç basamak var?"]},
{id:"hummel",r:"altstadt",t:"gez",n:"Hummel Hummel – Mors Mors!",xp:20,ll:[53.5523,9.9815],tags:["free"],
 why:"Hamburg'un gizli selamı. Su taşıyıcısı Hans Hummel'e çocuklar 'Hummel Hummel!' diye takılır, o da Platt dilinde 'Mors Mors!' (kıçımı öp) diye cevap verirmiş. Heykeli Rademachergang'da.",
 tip:"Heykelin yanında birine 'Hummel Hummel!' de, cevabı bekle. Şehirde başka renkli Hummel figürleri de var — bulduklarını say.",
 ph:["Hummel Hummel! — Mors Mors!","Hamburg'un şakalı selamı (Plattdeutsch)"],film:"Selamı kameraya yap, altyazıyla anlat — çok izlenir."},
{id:"deichstrasse",r:"altstadt",t:"gez",n:"Deichstraße",xp:20,ll:[53.5465,9.9875],tags:["free"],
 why:"Hamburg'un en eski tüccar evleri. 1842 Büyük Yangını burada, 42 numarada bir puro fabrikasında başladı ve şehrin üçte birini yaktı.",
 tip:"Arka taraftaki Nikolaifleet köprüsünden evlerin su tarafına bak — en güzel görüntü orada.",
 ph:["Hier hat der große Brand angefangen.","Büyük yangın burada başladı."]},
{id:"aalsuppe",r:"altstadt",t:"ye",n:"Hamburger Aalsuppe — Deichgraf",xp:30,ll:[53.5466,9.9873],tags:["klasik","rain"],pork:"Et suyu genelde jambon kemiğinden yapılır.",
 why:"İsmi 'yılan balığı çorbası' ama efsaneye göre 'Aal' Plattdeutsch 'all' yani 'her şey' demek: evde ne varsa içine girer. Sonradan turistler istedi diye içine gerçekten yılan balığı kondu.",
 tip:"Deichgraf (Deichstraße 23) Hamburg mutfağına adanmış klasik bir lokanta. Fiyatlar biraz yüksek; öğle menüsüne bak.",
 chef:"Tatlı-ekşi: jambon suyu, kuru armut/erik, sebze, otlar (Aalkraut), sirke, yılan balığı ve un köftesi (Schwemmklößchen). Türk mutfağındaki ekşili çorbalarla kıyasla.",
 ph:["Was ist in der Suppe drin?","Çorbada ne var?"]},
{id:"currywurst",r:"altstadt",t:"ye",n:"Currywurst — Mö-Grill",xp:20,ll:[53.5512,10.0012],tags:["night"],pork:"Sosis genelde domuz. Sor: 'Haben Sie Rindswurst oder Geflügelwurst?'",
 why:"Berlin icat ettiğini söyler; ama Hamburglu yazar Uwe Timm'in romanı 'Die Entdeckung der Currywurst' onu Hamburg'da doğmuş gösterir. Mö-Grill Mönckebergstraße'nin efsane büfesi.",
 tip:"Ayakta, hızlıca. 'Pommes rot-weiß' = patates kızartması ketçap + mayonez.",
 chef:"Curry sosunu evde dene: domates, soğan, elma püresi, köri, biraz sirke ve şeker. Her büfenin sırrı oranlarda.",
 ph:["Einmal Currywurst mit Pommes rot-weiß, bitte.","Bir currywurst, patates ketçap-mayonezli, lütfen."]},
{id:"plantenunblomen",r:"altstadt",t:"gez",n:"Planten un Blomen & Japon Bahçesi",xp:20,ll:[53.5600,9.9840],tags:["free"],
 why:"Şehrin ortasında 47 hektarlık park (ismi Platt dilinde 'bitkiler ve çiçekler'). Avrupa'nın büyük Japon bahçelerinden biri ve bir çay evi var.",
 tip:"Yazın parkta ücretsiz etkinlikler, kışın büyük açık hava buz pisti var.",
 ph:["Wie komme ich zum japanischen Garten?","Japon bahçesine nasıl giderim?"]},
{id:"wasserlicht",r:"altstadt",t:"yap",n:"Wasserlichtkonzert",xp:30,ll:[53.5594,9.9838],tags:["free","night"],months:[5,6,7,8,9],
 why:"Mayıs–Eylül her akşam parktaki gölde müzik eşliğinde ışıklı su gösterisi. Ücretsiz ve Hamburg yazının en tatlı ritüeli.",
 tip:"Mayıs–Ağustos 22:00, Eylül 21:00 civarı başlar (tarih ve saati parkın sitesinden kontrol et). 15 dk erken gidip göl kenarında yer kap.",
 ph:["Wann fängt das Konzert an?","Konser ne zaman başlıyor?"],film:"Tripod + uzun pozlama ya da slow-motion; müziği ayrıca kaydet."},
{id:"alsterrundfahrt",r:"altstadt",t:"yap",n:"Alster Tekne Turu",xp:30,ll:[53.5530,9.9935],tags:["view","ferry"],
 why:"Jungfernstieg'den kalkan beyaz Alster gemileriyle göl ve villalı kıyılar. Hamburg'u sudan tanımanın en kolay yolu.",
 tip:"Ücretli (yaklaşık 1 saat). Daha ucuzu: yaz aylarında Alster'de hat gibi çalışan 'Alsterkreuzfahrt'ta istediğin iskelede in-bin.",
 ph:["Wann fährt das nächste Schiff?","Bir sonraki gemi ne zaman kalkıyor?"]},
{id:"kunsthalle",r:"altstadt",t:"yap",n:"Hamburger Kunsthalle",xp:30,ll:[53.5558,10.0025],tags:["rain","museum"],
 why:"Almanya'nın en büyük sanat müzelerinden. Caspar David Friedrich'in ünlü 'Sis Denizi Üzerindeki Gezgin' tablosu burada.",
 tip:"Garın hemen yanında; yağmurlu bir pazar için ideal. Perşembe akşamları geç saate kadar açık olur — kontrol et.",
 ph:["Wo hängt der 'Wanderer über dem Nebelmeer'?","'Sis Denizi Üzerindeki Gezgin' nerede asılı?"]},

/* ---------------- SPEICHERSTADT & HAFENCITY ---------------- */
{id:"wasserschloss",r:"speicher",t:"gez",n:"Speicherstadt Kanalları & Wasserschloss",xp:20,ll:[53.5442,9.9978],tags:["free","night"],
 why:"Dünyanın en büyük tarihi depo kompleksi (1883–1927). Kahve, çay, baharat ve halı burada depolanırdı.",
 tip:"Poggenmühlenbrücke'den Wasserschloss'a bak: Hamburg'un en çok fotoğraflanan karesi. Akşam ışıklar yanınca (mavi saat) git.",
 ph:["Können Sie ein Foto von mir machen?","Benim bir fotoğrafımı çekebilir misiniz?"],film:"Mavi saatte köprüden sabit plan + timelapse: ışıklar tek tek yanıyor."},
{id:"wunderland",r:"speicher",t:"yap",n:"Miniatur Wunderland",xp:40,ll:[53.5437,9.9886],tags:["rain","museum"],
 why:"Dünyanın en büyük model demiryolu: kilometrelerce ray, minik havaalanında kalkan uçaklar, gece-gündüz döngüsü.",
 tip:"Online zaman dilimi ayırt; sabah ilk saat ya da akşam son saatler daha sakin. En az 3 saat ayır.",
 ph:["Ich habe online reserviert.","Online rezervasyon yaptım."],film:"Makro çekim: minik figürlerin içinde gizli şakaları bul."},
{id:"elphi-plaza",r:"speicher",t:"gez",n:"Elbphilharmonie Plaza",xp:30,ll:[53.5413,9.9842],tags:["view","free"],
 why:"2017'de açılan konser salonu, eski bir kakao deposunun üstüne oturtuldu. 37 m'deki Plaza binanın çevresini dolaşan açık teras.",
 tip:"Plaza bileti yerinde ücretsiz (online ayırtmak küçük bir ücret). 82 m'lik kavisli yürüyen merdiven 'Tube'u kaçırma. Gün batımına doğru git.",
 ph:["Ein Ticket für die Plaza, bitte.","Plaza için bir bilet, lütfen."],film:"Tube'da yukarı çıkarken sabit kamera — sonunda pencereden Elbe çıkıyor."},
{id:"elphi-konzert",r:"speicher",t:"yap",n:"Elbphilharmonie'de Konser",xp:50,ll:[53.5413,9.9842],tags:["night","rain"],
 why:"Dünyanın en iyi akustiğe sahip salonlarından birinde canlı müzik. Sadece klasik değil: caz, dünya müziği, elektronik de var.",
 tip:"En ucuz kategoriler gerçekten uygun ama satışa çıkınca hemen biter; siteden bülten aboneliği yap. İptal biletleri için konser günü sabahı kontrol et.",
 ph:["Gibt es noch Restkarten?","Hâlâ kalan bilet var mı?"]},
{id:"kaffeeroesterei",r:"speicher",t:"ye",n:"Kaffeerösterei Speicherstadt",xp:20,ll:[53.5440,9.9878],tags:["rain"],
 why:"Eski bir depoda kahve kavurma dükkanı + kafe. Speicherstadt bir zamanlar dünyanın en büyük kahve depolarından biriydi.",
 tip:"Kavurma makinesinin yanındaki masaya otur. Çekirdek alıp evde dene.",
 chef:"Kavurma derecelerini sor (helle/dunkle Röstung). Filtre kahve kültürü Almanya'da güçlü — French press ve pour-over dene.",
 ph:["Welche Bohne empfehlen Sie für Filterkaffee?","Filtre kahve için hangi çekirdeği önerirsiniz?"]},
{id:"spicys",r:"speicher",t:"yap",n:"Spicy's Gewürzmuseum",xp:30,ll:[53.5436,9.9905],tags:["rain","museum"],
 why:"Dünyada baharata adanmış tek müze olduğunu söyler: yüzlerce baharatı koklayıp, dokunup, tadabilirsin. Aşçı için birebir.",
 tip:"Am Sandtorkai'de, Speicherstadtmuseum'un yakınında. Küçük ama 1 saat yeter. Dükkanında iyi baharat var.",
 chef:"Almanların 'Gewürz' isimlerini öğren: Kreuzkümmel (kimyon), Pfeffer (karabiber), Paprika edelsüß (tatlı pul biber), Zimt (tarçın), Nelke (karanfil). İş yerinde lazım olacak!",
 ph:["Wie heißt dieses Gewürz auf Deutsch?","Bu baharatın Almancası ne?"]},
{id:"speichermuseum",r:"speicher",t:"yap",n:"Speicherstadtmuseum",xp:20,ll:[53.5436,9.9910],tags:["rain","museum"],
 why:"Gerçek bir depo katında kahve çuvalları, çay sandıkları, kauçuk balyaları: depo işçilerinin ('Quartiersleute') dünyası.",
 tip:"Bazı günler kahve tadımı yapılıyor — siteye bak.",
 ph:["Was haben die Quartiersleute gemacht?","Depo işçileri ne iş yapardı?"]},
{id:"maritim",r:"speicher",t:"yap",n:"Internationales Maritimes Museum",xp:30,ll:[53.5436,10.0018],tags:["rain","museum"],
 why:"Eski bir depo binasının 10 katında 3000 yıllık denizcilik tarihi: binlerce gemi maketi, Lego'dan dev Queen Mary 2.",
 tip:"Yağmurlu gün planı. En üst kattan başla, aşağı in.",
 ph:["Wo ist der Aufzug?","Asansör nerede?"]},
{id:"hafencity",r:"speicher",t:"gez",n:"HafenCity Yürüyüşü",xp:20,ll:[53.5410,9.9960],tags:["free"],
 why:"Avrupa'nın en büyük şehir dönüşüm projelerinden biri. Marco-Polo-Terrassen, Strandkai ve yeni Überseequartier.",
 tip:"Elbphilharmonie'den doğuya Magellan- ve Marco-Polo-Terrassen'e yürü; basamaklarda oturup gemileri izle.",
 ph:["Ist das hier alles neu gebaut?","Buradaki her şey yeni mi yapıldı?"]},
{id:"lohsepark",r:"speicher",t:"gez",n:"Denkmal Hannoverscher Bahnhof",xp:20,ll:[53.5408,10.0075],tags:["free"],
 why:"1940–1945 arasında 8.000'den fazla Yahudi, Roman ve Sinti buradan sürgün edildi. Lohsepark'taki anıt ve 'Fuge' sessiz ama çok güçlü.",
 tip:"Saygıyla gez; bilgi panolarını oku. Yakındaki 'dokumentationszentrum' da açıldıysa uğra.",
 ph:["Wir dürfen das nicht vergessen.","Bunu unutmamalıyız."]},
{id:"dialog",r:"speicher",t:"yap",n:"Dialog im Dunkeln",xp:30,ll:[53.5466,10.0005],tags:["rain"],
 why:"Tamamen karanlıkta, görme engelli bir rehberle şehir, pazar ve kafe deneyimi. Dil öğrenen biri için de harika: sadece kulakla Almanca!",
 tip:"Online rezervasyon. Rehbere Almanca turu seçersen gerçek bir dil sınavı olur.",
 ph:["Können Sie bitte langsamer sprechen?","Lütfen daha yavaş konuşur musunuz?"]},

/* ---------------- LANDUNGSBRÜCKEN & HAFEN ---------------- */
{id:"bruecke10",r:"hafen",t:"ye",n:"Brücke 10 — Krabbenbrötchen",xp:20,ll:[53.5453,9.9683],tags:["fisch"],
 why:"Landungsbrücken'in suya bakan en sevilen balık büfesi; birçok listede 'şehrin en iyi karidesli sandviçi'.",
 tip:"Klasikler: Bismarckhering, Matjes, Backfisch, Lachs. Kuyruk normal, hızlı ilerler. Martılara dikkat — sandviçini kaparlar!",
 chef:"Nordseekrabben (gri karides) teknede haşlanır, kabukları elle soyulur; çoğu soyulmak için Fas'a gönderilip geri gelir. Taze soyulmuş olanı tatlıdır.",
 ph:["Ein Krabbenbrötchen, bitte. Mit Zwiebeln.","Bir karidesli sandviç, lütfen. Soğanlı."],film:"Sandviç + arkada geçen gemi + martı — klasik Hamburg karesi."},
{id:"faehre62",r:"hafen",t:"yap",n:"Fähre 62 ile 'Fakir Liman Turu'",xp:30,ll:[53.5456,9.9700],tags:["ferry","free","view"],
 why:"HADAG feribotları toplu taşımanın parçası: Deutschlandticket ya da HVV biletiyle ekstra para yok. 62 hattı Landungsbrücken'den Finkenwerder'e liman boyunca gider.",
 tip:"Landungsbrücken Brücke 3'ten bin, üst güverteye çık. Övelgönne'de (Neumühlen) inip kumsala yürüyebilirsin.",
 ph:["Fährt diese Fähre nach Finkenwerder?","Bu feribot Finkenwerder'e gidiyor mu?"],film:"Arka güverteden Elbphilharmonie'nin uzaklaştığı plan."},
{id:"elbtunnel",r:"hafen",t:"gez",n:"Alter Elbtunnel",xp:20,ll:[53.5457,9.9662],tags:["free","rain"],
 why:"1911'de açılan, Elbe'nin 24 m altından geçen fayanslı tünel. Arabalar hâlâ dev asansörlerle iniyor.",
 tip:"Yürüyerek karşıya geç (~430 m). Güney çıkışından (Steinwerder) Landungsbrücken ve Michel manzarası müthiş.",
 ph:["Ist der Tunnel für Fußgänger offen?","Tünel yayalara açık mı?"],film:"Güney çıkışından panorama — şehir silüeti tek karede."},
{id:"michel",r:"hafen",t:"gez",n:"Michel (St. Michaelis)",xp:30,ll:[53.5484,9.9788],tags:["view","rain"],
 why:"Hamburg'un sembolü; 132 m kule asırlarca Elbe'ye giren denizcilere işaret oldu. Barok iç mekanı çok aydınlık.",
 tip:"106 m'deki platforma 452 basamakla ya da asansörle çık. Kulenin saati Almanya'nın en büyük kule saati.",
 ph:["Gibt es einen Aufzug zum Turm?","Kuleye asansör var mı?"]},
{id:"labskaus",r:"hafen",t:"ye",n:"Labskaus — Old Commercial Room",xp:40,ll:[53.5491,9.9772],tags:["klasik","rain"],pork:"Genelde dana (Corned Beef) — yine de sor.",
 why:"1795'ten beri Michel'in karşısında; 'Almanya'nın en eski Labskaus lokantası' olarak bilinir. Labskaus Hamburg denizcilerinin yemeği.",
 tip:"Görünüşü pembe bir püre — önyargıyı bırak. Yanında sahanda yumurta, Rollmops (sirkeli ringa) ve turşu gelir.",
 chef:"Corned beef + haşlanmış patates + pancar (Rote Bete) + soğan, ezilir; bazen ringa eklenir. Gemilerde taze et olmadığı için tuzlu et kullanılırdı. Evde kendi versiyonunu yap!",
 ph:["Einmal Labskaus, bitte.","Bir Labskaus, lütfen."]},
{id:"portugiesen",r:"hafen",t:"ye",n:"Portugiesenviertel — Pastel de Nata",xp:20,ll:[53.5468,9.9740],tags:[],
 why:"Landungsbrücken ile Michel arasındaki birkaç sokak: 1970'lerden beri Portekizli ve İspanyol lokantalarıyla dolu.",
 tip:"Ditmar-Koel-Straße ve çevresinde bir kafede Pastel de Nata + galão (sütlü kahve). Akşam ızgara balık için de iyi.",
 chef:"Izgara sardalya ve ahtapot dene; Portekiz mutfağının 'bacalhau' (tuzlu morina) tekniklerini sor.",
 ph:["Zwei Pastéis de Nata zum Mitnehmen.","İki Pastel de Nata, paket."]},
{id:"museumsschiffe",r:"hafen",t:"yap",n:"Rickmer Rickmers & Cap San Diego",xp:30,ll:[53.5443,9.9760],tags:["rain","museum"],
 why:"Biri 1896 yapımı üç direkli yelkenli, diğeri 1961 yapımı dünyanın en büyük yüzen müze yük gemisi.",
 tip:"İkisi de Landungsbrücken'de yan yana. Cap San Diego'nun makine dairesini kaçırma.",
 ph:["Darf man hier fotografieren?","Burada fotoğraf çekmek serbest mi?"]},
{id:"stintfang",r:"hafen",t:"gez",n:"Stintfang Manzarası",xp:20,ll:[53.5476,9.9708],tags:["free","view","night"],
 why:"Landungsbrücken'in hemen üstündeki tepe (gençlik hostelinin önü). Liman, vinçler ve Elbe ayağının altında.",
 tip:"Gün batımında git; şehir ışıkları yanana kadar kal.",
 ph:["Was für ein Ausblick!","Ne manzara ama!"],film:"Timelapse: gündüzden geceye liman."},
{id:"krameramt",r:"hafen",t:"gez",n:"Krameramtsstuben",xp:20,ll:[53.5489,9.9800],tags:["free"],
 why:"17. yüzyıldan kalan küçük yarı-ahşap evler: esnaf loncası dul eşleri için yapılmıştı. Michel'in dibinde saklı bir avlu.",
 tip:"Michel'e giderken 2 dakikalık sapma. Dar geçitte sessiz ol, burada insanlar yaşıyor.",
 ph:["Wohnen hier noch Leute?","Burada hâlâ insanlar yaşıyor mu?"]},
{id:"barkasse",r:"hafen",t:"yap",n:"Barkasse ile Liman Turu",xp:30,ll:[53.5455,9.9720],tags:["view","ferry"],
 why:"Büyük tur gemileri yerine küçük 'Barkasse' teknelerini seç: yüksek suda Speicherstadt kanallarına girebiliyorlar.",
 tip:"Landungsbrücken'de pazarlık yapan 'Hummel'ler (davetçiler) var — fiyatı netleştir. Akşamki 'Lichterfahrt' (ışık turu) çok güzel.",
 ph:["Fahren Sie auch durch die Speicherstadt?","Speicherstadt'tan da geçiyor musunuz?"]},
{id:"musical",r:"hafen",t:"yap",n:"Hamburg Müzikali (König der Löwen)",xp:40,ll:[53.5424,9.9695],tags:["night","rain","ferry"],
 why:"Hamburg Broadway ve West End'den sonra dünyanın büyük müzikal şehirlerinden. Aslan Kral'ın tiyatrosuna Landungsbrücken'den özel feribotla gidiliyor!",
 tip:"Bilet pahalı olabilir; hafta içi ve son dakika fırsatlarına bak. Feribot yolculuğu bile deneyim.",
 ph:["Gibt es günstigere Plätze?","Daha ucuz yerler var mı?"]},

/* ---------------- ST. PAULI ---------------- */
{id:"fischmarkt",r:"stpauli",t:"yap",n:"Hamburger Fischmarkt (Pazar sabahı)",xp:50,ll:[53.5452,9.9530],tags:["market","fisch","free"],
 why:"1703'ten beri her pazar sabahı. Marktschreier'ler (bağıran satıcılar) meyve sepetlerini açık artırma gibi satar; Fischauktionshalle'de canlı müzikle kahvaltı.",
 tip:"Nisan–Ekim 05:00–09:30, Kasım–Mart 07:00–09:30. Gece Reeperbahn'dan gelenlerle sabahçılar burada buluşur. Kapanışa doğru fiyatlar düşer.",
 chef:"Toptan fiyata balık ve meyve; tezgahlarda Aal (yılan balığı), Räucherfisch (füme balık) ve Matjes kokla, sor, tat.",
 ph:["Was kostet das? — Geht's noch billiger?","Bu ne kadar? — Daha ucuz olur mu?"],film:"Marktschreier'i çek — en eğlenceli vlog içeriği. Gün doğumu + Elbe."},
{id:"reeperbahn",r:"stpauli",t:"gez",n:"Reeperbahn & Spielbudenplatz",xp:20,ll:[53.5495,9.9625],tags:["free","night"],
 why:"İsmi halat yapımcılarından (Reepschläger) geliyor: halat yapmak için uzun düz yol lazımdı. Bugün Avrupa'nın en ünlü eğlence caddelerinden.",
 tip:"Akşam yürü; Davidwache karakolunu ve Spielbudenplatz'ı gör. Herbertstraße'ye kadınların ve 18 yaş altının girişi yasak, fotoğraf da yasak — saygı.",
 ph:["Wo ist hier eine gute Bar ohne Touristen?","Turistsiz iyi bir bar nerede?"]},
{id:"beatles",r:"stpauli",t:"gez",n:"Beatles-Platz & Große Freiheit",xp:20,ll:[53.5500,9.9579],tags:["free","night"],
 why:"Beatles 1960–62 arasında Hamburg'da Indra, Kaiserkeller ve Star-Club'da çalarak olgunlaştı. John Lennon: 'Liverpool'da doğdum ama Hamburg'da büyüdüm.'",
 tip:"Plak şeklindeki meydandan Große Freiheit'a gir; Indra hâlâ açık ve küçük konserler veriyor.",
 ph:["Spielt heute Abend eine Band?","Bu akşam bir grup çalıyor mu?"]},
{id:"bunker",r:"stpauli",t:"gez",n:"Grüner Bunker (Feldstraße)",xp:30,ll:[53.5566,9.9697],tags:["free","view"],
 why:"II. Dünya Savaşı uçaksavar bunkeri; üzerine ağaçlarla dolu bir çatı bahçesi kuruldu. 58 m'den şehir manzarası ücretsiz.",
 tip:"560 m'lik 'Bergpfad' spiral yoluyla çık. Mayıs–Eylül 9–21, Ekim–Nisan 9–17. Hafta sonu kuyruk olabilir.",
 ph:["Wie lange muss man warten?","Ne kadar beklemek gerekiyor?"],film:"Spiral yolda çıkarken bina etrafında dönen tek plan."},
{id:"millerntor",r:"stpauli",t:"yap",n:"FC St. Pauli — Millerntor",xp:40,ll:[53.5546,9.9677],tags:["night"],
 why:"Kafatası logosu, punk müzik, anti-faşist taraftarlar: dünyanın en 'farklı' futbol kulüplerinden. Maç günü mahalle ayağa kalkar.",
 tip:"Maç biletleri neredeyse imkansız; stadyum turu, Fanladen ya da bir Kiez barında maçı izlemek de sayılır.",
 ph:["Wer spielt heute? — Wie steht's?","Bugün kim oynuyor? — Skor ne?"]},
{id:"parkfiction",r:"stpauli",t:"gez",n:"Park Fiction & Hafenstraße",xp:20,ll:[53.5468,9.9580],tags:["free","view"],
 why:"Mahalle sakinlerinin mücadelesiyle yapılmış park: plastik palmiyeler, Elbe ve vinç manzarası. Yandaki Hafenstraße evleri 80'lerin işgal hareketinin simgesi.",
 tip:"Gün batımında git; Balduintreppe merdivenlerinden aşağı in.",
 ph:["Ist das hier ein öffentlicher Park?","Burası halka açık bir park mı?"],film:"Palmiye + dev konteyner gemisi aynı karede."},
{id:"pannfisch",r:"stpauli",t:"ye",n:"Pannfisch — Fischerhaus",xp:30,ll:[53.5452,9.9573],tags:["klasik","fisch"],pork:"Bratkartoffeln'e Speck (domuz pastırması) eklenebilir: 'Ohne Speck, bitte.'",
 why:"Fischmarkt'ın karşısındaki klasik balık lokantası. Pannfisch: 'tavadaki balık' — eskiden günün artan balıklarından yapılan Hamburg ev yemeği.",
 tip:"Pazar sabahı Fischmarkt'tan sonra gitmek klasik. Hafta içi öğlen daha sakin.",
 chef:"Birkaç cins balık filetosu tereyağında kızarır; hardal sosu (Senfsoße) ve kızarmış patates (Bratkartoffeln) ile gelir. Hardal sosunu incele: hardal, krema, balık suyu, biraz şeker.",
 ph:["Ist der Fisch heute frisch?","Balık bugün taze mi?"]},
{id:"rindermarkthalle",r:"stpauli",t:"ye",n:"Rindermarkthalle St. Pauli",xp:20,ll:[53.5574,9.9668],tags:["rain","market"],
 why:"Eski sığır pazarı binası, bugün market + yemek alanı. Farklı mutfaklardan tezgahlar, yerel üreticiler.",
 tip:"Feldstraße U3'ün hemen yanında; Grüner Bunker ile birleştir.",
 chef:"Alman süpermarketlerinde göremediğin yerel ürünleri incele; fiyat karşılaştır (Cüzdan'a not al 😉).",
 ph:["Woher kommt das Gemüse?","Sebzeler nereden geliyor?"]},
{id:"flohschanze",r:"stpauli",t:"yap",n:"Flohschanze Bit Pazarı (Cumartesi)",xp:20,ll:[53.5577,9.9672],tags:["market","free"],
 why:"Her cumartesi eski mezbaha alanında Hamburg'un en sevilen bit pazarı: plak, vintage, mutfak eşyası.",
 tip:"Sabah erken git. İkinci el bıçak, döküm tava, emaye tencere avla — aşçı için hazine.",
 chef:"Eski Alman mutfak aletleri (Spätzlepresse, Fleischwolf) çok ucuza çıkar.",
 ph:["Machen Sie mir einen besseren Preis?","Bana daha iyi bir fiyat yapar mısınız?"]},
{id:"kleinehaie",r:"stpauli",t:"ye",n:"Kleine Haie Große Fische — Gece Balığı",xp:20,ll:[53.5490,9.9600],tags:["fisch","night"],
 why:"Kiez'de gece geç saate kadar açık balık dükkanı: Cuma–Cumartesi gecesi Reeperbahn'dan sonra Fischbrötchen.",
 tip:"Açılış saatlerini kontrol et; hafta sonu gecesi asıl zamanı.",
 ph:["Haben Sie noch offen?","Hâlâ açık mısınız?"]},
{id:"panoptikum",r:"stpauli",t:"yap",n:"Panoptikum",xp:20,ll:[53.5493,9.9640],tags:["rain","museum"],
 why:"1879'dan beri Almanya'nın en eski balmumu müzesi; tarihî Alman figürlerini tanımak için eğlenceli bir yol.",
 tip:"Spielbudenplatz'da. Tanımadığın figürlerin kim olduğunu Almanca açıklamalardan çıkar — kelime avı.",
 ph:["Wer ist das?","Bu kim?"]},

/* ---------------- ST. GEORG ---------------- */
{id:"langereihe",r:"stgeorg",t:"ye",n:"Lange Reihe & Café Gnosa",xp:20,ll:[53.5573,10.0148],tags:["rain"],
 why:"St. Georg'un ana caddesi: kafeler, küçük dükkanlar, şehrin gökkuşağı mahallesi. Café Gnosa 1930'lardan kalma bir pastane-kafe.",
 tip:"Bir dilim Torte + kahve: 'Kaffee und Kuchen' Alman öğleden sonra ritüelini öğren.",
 chef:"Alman pasta isimleri: Käsekuchen, Bienenstich, Schwarzwälder Kirschtorte, Streuselkuchen. Birini seç, katlarını analiz et.",
 ph:["Ein Stück Käsekuchen und einen Kaffee, bitte.","Bir dilim cheesecake ve bir kahve, lütfen."]},
{id:"mutterland",r:"stgeorg",t:"ye",n:"Mutterland — Franzbrötchen",xp:20,ll:[53.5535,10.0085],tags:["franz"],
 why:"Kuzey Alman yerel ürünleri dükkanı; Franzbrötchen'i klasik, çikolatalı, elmalı ve krem peynirli yapıyorlar.",
 tip:"Franzbrötchen Hamburg'un simgesi: kruvasan hamuru, tarçın-şeker, ortadan bastırılmış. Klasikle başla.",
 chef:"Plunderteig (kat kat mayalı hamur) + tereyağı + tarçın-şeker; rulo yapılıp kesilir, sapla ortadan bastırılır. Efsaneye göre Fransız işgali (1806–1814) döneminde doğdu.",
 ph:["Ein Franzbrötchen, bitte. Ist es noch warm?","Bir Franzbrötchen, lütfen. Hâlâ sıcak mı?"]},
{id:"steindamm",r:"stgeorg",t:"ye",n:"Steindamm — Sıla Kokusu",xp:20,ll:[53.5555,10.0130],tags:[],
 why:"Garın arkasındaki cadde: Türk, Arap, Afgan, Hint marketleri ve helal kasaplar. Memleketi özlediğinde ya da özel baharat lazım olduğunda.",
 tip:"Türkçe konuşmak serbest ama burada da Almanca pratik yap 😉. Akşam kalabalık; dikkatli ol.",
 chef:"Almanya'da bulması zor malzemeler (pul biber, nar ekşisi, kaşar, sucuk) için fiyat karşılaştır.",
 ph:["Ist das Fleisch halal?","Bu et helal mi?"]},
{id:"schifferboerse",r:"stgeorg",t:"ye",n:"Schifferbörse — Birnen, Bohnen und Speck",xp:30,ll:[53.5532,10.0092],tags:["klasik","rain"],pork:"Speck = domuz pastırması. Bu yemeğin özü domuz; tatmak istemezsen menüden balık seç.",
 why:"Garın karşısında, gemi maketleriyle dolu geleneksel Hamburg lokantası. Yaz sonu (Ağustos–Eylül) sezonluk 'Birnen, Bohnen und Speck' (armut-fasulye-pastırma) yapılır.",
 tip:"Sezon dışında Labskaus, Matjes ya da Scholle de var.",
 chef:"Tatlı-tuzlu kuzey kombinasyonu: küçük pişirme armutları, yeşil fasulye, pastırma, maydanozlu patates. Türk mutfağında karşılığı yok — tatlı/tuzlu dengeyi incele.",
 ph:["Was ist heute das Tagesgericht?","Bugünün günlük yemeği ne?"]},
{id:"wischer",r:"stgeorg",t:"ye",n:"Daniel Wischer — Backfisch",xp:20,ll:[53.5526,10.0068],tags:["fisch"],
 why:"Hamburg'un eski balık kızartma geleneklerinden; Hauptbahnhof'taki şubesinde trene binmeden hızlı Backfisch.",
 tip:"'Backfisch mit Kartoffelsalat' klasik kombinasyon. Kuzey Alman patates salatası mayonezlidir.",
 chef:"Hamur (Backteig) tarifini incele: bira ya da maden suyu ile hafif ve çıtır olur.",
 ph:["Mit Kartoffelsalat oder Pommes?","Patates salatasıyla mı patates kızartmasıyla mı?"]},
{id:"deichtorhallen",r:"stgeorg",t:"yap",n:"Deichtorhallen — Haus der Photographie",xp:30,ll:[53.5470,10.0060],tags:["rain","museum"],
 why:"Eski pazar halleri: biri çağdaş sanat, diğeri Avrupa'nın büyük fotoğraf müzelerinden. Video çeken biri için ilham deposu.",
 tip:"Sergiler sık değişir; sitesinden güncel sergiye bak.",
 ph:["Was ist die aktuelle Ausstellung?","Güncel sergi ne?"]},
{id:"mkg",r:"stgeorg",t:"yap",n:"Museum für Kunst und Gewerbe",xp:30,ll:[53.5515,10.0095],tags:["rain","museum"],
 why:"Tasarım, moda, Japon sanatı, Art Nouveau... İçinde gerçek bir Japon çay evi var.",
 tip:"Garın hemen yanında; yağmurlu bir akşamüstü için.",
 ph:["Wo ist die Garderobe?","Vestiyer nerede?"]},
{id:"franzfriends",r:"stgeorg",t:"ye",n:"Franz & Friends — Hauptbahnhof",xp:20,ll:[53.5530,10.0063],tags:["franz"],
 why:"Garın Wandelhalle'sinde Franzbrötchen'e adanmış küçük dükkan; birçok çeşit.",
 tip:"Trene binerken al. Franzbrötchen Jürisi rozeti için karşılaştır!",
 ph:["Welche Sorte ist die beliebteste?","En sevilen çeşit hangisi?"]},

/* ---------------- SCHANZE & KAROVIERTEL ---------------- */
{id:"roteflora",r:"schanze",t:"gez",n:"Schulterblatt & Rote Flora",xp:20,ll:[53.5622,9.9632],tags:["free"],
 why:"1888 yapımı tiyatro; 1989'dan beri işgal edilmiş otonom kültür merkezi. Grafitiler, kafeler, Schanze'nin kalbi.",
 tip:"Schulterblatt'ta yürü, yan sokaklardaki küçük dükkanlara gir.",
 ph:["Was ist die Rote Flora?","Rote Flora nedir?"],film:"Grafiti duvarları önünde walking-vlog."},
{id:"bullerei",r:"schanze",t:"ye",n:"Bullerei — Tim Mälzer",xp:40,ll:[53.5627,9.9696],tags:["rain"],pork:"Et ağırlıklı menü; domuz yemekleri var, sor.",
 why:"Almanya'nın en ünlü TV şeflerinden Tim Mälzer'in, eski mezbaha binasındaki restoranı. Bir aşçı için hac yeri.",
 tip:"Restoran için rezervasyon; daha ucuz deneyim için yanındaki 'Deli' bölümü.",
 chef:"Açık mutfağı izle: hız, servis düzeni, tabak sunumu. Almanya'da mutfakta iş ararken bu tür yerlerin 'Ausbildung'/iş ilanlarına bak.",
 ph:["Ich bin auch Koch. Darf ich kurz in die Küche schauen?","Ben de aşçıyım. Mutfağa kısaca bakabilir miyim?"]},
{id:"altesmaedchen",r:"schanze",t:"ye",n:"Altes Mädchen & Ratsherrn",xp:20,ll:[53.5625,9.9700],tags:["rain","night"],
 why:"Hamburg'un zanaat birası Ratsherrn'in bira salonu. Alkol içmiyorsan: Hamburg markası Fritz-Kola ya da alkolsüz bira.",
 tip:"Yanındaki Ratsherrn dükkanında bira turu/şişe seçimi var.",
 chef:"Bira ile yemek eşleştirmesi (Bierpairing) Alman mutfaklarında çok soruluyor; temel stilleri öğren: Pils, Helles, Weizen, IPA.",
 ph:["Haben Sie auch alkoholfreies Bier?","Alkolsüz biranız da var mı?"]},
{id:"elbgold",r:"schanze",t:"ye",n:"Elbgold — Kahve & Franzbrötchen",xp:20,ll:[53.5630,9.9690],tags:["franz","rain"],
 why:"Hamburg'un en bilinen nitelikli kahve kavurucularından; Franzbrötchen'leri elle sarılıyor.",
 tip:"Schanzenhöfe'deki kavurma evine git; barista ile kahve hakkında sohbet et.",
 ph:["Einen Flat White, bitte.","Bir flat white, lütfen."]},
{id:"schanzenpark",r:"schanze",t:"gez",n:"Sternschanzenpark & Wasserturm",xp:20,ll:[53.5655,9.9695],tags:["free"],
 why:"1910 yapımı dev su kulesi bugün bir otel. Yazın park çimlerinde Hamburgluların piknik ve mangal hayatı.",
 tip:"Hava güzelse bir şeyler alıp çimlere uzan; Almanlarla tanışmanın kolay yolu.",
 ph:["Ist hier noch frei?","Burası boş mu?"]},
{id:"karoviertel",r:"schanze",t:"gez",n:"Karoviertel — Marktstraße",xp:20,ll:[53.5585,9.9655],tags:["free"],
 why:"Küçük tasarım dükkanları, vintage, plakçılar. Schanze'den daha sakin ve yerel.",
 tip:"Marktstraße'yi baştan sona yürü; Flohschanze ile aynı cumartesiye koy.",
 ph:["Haben Sie das auch in Größe M?","Bunun M bedeni de var mı?"]},
{id:"cornern",r:"schanze",t:"yap",n:"'Cornern' — Köşe Kültürü",xp:20,ll:[53.5618,9.9628],tags:["free","night"],
 why:"Hamburg'a özgü: yaz akşamları insanlar bara değil, Kiosk'tan içecek alıp sokak köşelerinde oturur. Ucuz ve sosyal.",
 tip:"Schulterblatt köşelerinde bir Kiosk'tan Mate ya da Fritz-Kola al, kalabalığa karış, biriyle Almanca konuş.",
 ph:["Woher kommst du? — Ich komme aus der Türkei.","Nerelisin? — Türkiye'denim."]},

/* ---------------- ALTONA & OTTENSEN ---------------- */
{id:"altonabalkon",r:"altona",t:"gez",n:"Altonaer Balkon",xp:20,ll:[53.5450,9.9375],tags:["free","view","night"],
 why:"Elbe'ye bakan yeşil tepe: Köhlbrandbrücke, konteyner vinçleri ve gemiler. Altona 1864'e kadar Danimarka'ya aitti!",
 tip:"Gün batımında bank kap. Elbe'nin karşısındaki terminal ışıklarını izle.",
 ph:["Gehörte Altona früher zu Dänemark?","Altona eskiden Danimarka'ya mı aitti?"],film:"Gün batımı + vinçlerin silüeti."},
{id:"ottensen",r:"altona",t:"gez",n:"Ottensen Sokakları",xp:20,ll:[53.5530,9.9300],tags:["free"],
 why:"Eski sanayi işçi mahallesi; bugün kafeler, ikinci el dükkanları ve kültür merkezi 'Fabrik'. Eskiden kalabalık bir Türk topluluğu vardı.",
 tip:"Spritzenplatz'dan başla, Ottenser Hauptstraße ve yan sokaklarda kaybol.",
 ph:["Kennst du ein gutes Café hier?","Burada iyi bir kafe biliyor musun?"]},
{id:"altonaermuseum",r:"altona",t:"yap",n:"Altonaer Museum",xp:20,ll:[53.5500,9.9350],tags:["rain","museum"],
 why:"Kuzey Almanya kıyı kültürü: gemi pruva figürleri, balıkçı evleri, eski çiftlik mutfakları.",
 tip:"Restore edilmiş tarihî Vierlande mutfağı bölümüne bak.",
 chef:"Eski kuzey mutfaklarında tütsüleme ve tuzlama teknikleri — bugünkü Räucherfisch kültürünün kökeni.",
 ph:["Ist das eine alte Küche?","Bu eski bir mutfak mı?"]},
{id:"madeleine",r:"altona",t:"ye",n:"Patisserie Madeleine — Franzbrötchen",xp:20,ll:[53.5555,9.9255],tags:["franz"],
 why:"Fransız pastacılığı ile Hamburg klasiğinin buluşması; Ottensen'de küçük bir patisserie.",
 tip:"Franzbrötchen'in yanında bir Madeleine al, ikisini karşılaştır.",
 ph:["Was empfehlen Sie heute?","Bugün ne önerirsiniz?"]},
{id:"atlantik",r:"altona",t:"ye",n:"Atlantik Fisch — Große Elbstraße",xp:20,ll:[53.5452,9.9405],tags:["fisch"],
 why:"Balıkçı limanı hattındaki balıkçı + bistro: Nordseekrabben, Matjes, çıtır Backfisch sandviçler.",
 tip:"Große Elbstraße boyunca Fischmarkt'a doğru yürü — balık toptancıları sırayla dizili.",
 ph:["Ist das Matjes?","Bu Matjes mi?"]},
{id:"fischereihafen",r:"altona",t:"ye",n:"Fischereihafen Restaurant",xp:40,ll:[53.5448,9.9390],tags:["fisch","klasik"],
 why:"Elbe kıyısında, uzun yıllardır Hamburg'un en bilinen balık restoranlarından. Özel gün yeri.",
 tip:"Pahalı; öğle menüsü daha uygun. Pencere kenarı iste.",
 chef:"Klasik Alman balık servisini izle: Seezunge Müllerin Art (dil balığı, tereyağlı), Steinbutt (kalkan).",
 ph:["Einen Tisch am Fenster, bitte.","Pencere kenarında bir masa, lütfen."]},
{id:"dockland",r:"altona",t:"gez",n:"Dockland",xp:20,ll:[53.5443,9.9335],tags:["free","view"],
 why:"Gemi pruvası şeklindeki ofis binası; dış merdivenlerle çatı terasına çıkıp limanı izleyebilirsin.",
 tip:"Fischmarkt sabahından sonra yürü; çatıdan Elbe'nin iki yönü de görünür.",
 ph:["Darf man aufs Dach?","Çatıya çıkmak serbest mi?"],film:"Merdivenden çıkış + çatıda 360° dönüş."},

/* ---------------- ELBSTRAND ---------------- */
{id:"strandperle",r:"elbstrand",t:"ye",n:"Strandperle",xp:20,ll:[53.5450,9.9130],tags:["view"],
 why:"Elbe kumsalında efsane büfe-bar: ayakların kumda, 400 m'lik konteyner gemileri birkaç yüz metre önünden geçiyor.",
 tip:"Güneşli hafta sonu çok kalabalık; hafta içi akşamüstü git.",
 ph:["Ist der Platz hier frei?","Bu yer boş mu?"],film:"Dev gemi geçerken alçak açı, ön planda kum."},
{id:"museumshafen",r:"elbstrand",t:"gez",n:"Museumshafen Övelgönne & Kaptan Evleri",xp:20,ll:[53.5440,9.9200],tags:["free"],
 why:"Eski buharlı ve yelkenli gemilerin yattığı müze limanı; arkasında küçük bahçeli kaptan evleri sıralı.",
 tip:"Neumühlen iskelesinde in (Fähre 62), Övelgönne yolunu batıya yürü.",
 ph:["Wie alt ist das Schiff?","Bu gemi kaç yaşında?"]},
{id:"elbwanderung",r:"elbstrand",t:"yap",n:"Elbe Yürüyüşü: Övelgönne → Blankenese",xp:40,ll:[53.5560,9.8600],rad:2500,tags:["free"],
 why:"~9 km kumsal + orman yolu. Hamburg'un en güzel yürüyüşlerinden; yol boyunca kafeler var.",
 tip:"Övelgönne'den başla, Blankenese'de bitir, dönüşü S-Bahn ya da 62+Blankenese feribotuyla yap.",
 ph:["Wie weit ist es noch bis Blankenese?","Blankenese'ye daha ne kadar var?"],film:"Uzun yürüyüş vlogu: başlangıç-orta-son, adım sayısı ekranda."},
{id:"nuggis",r:"elbstrand",t:"ye",n:"Nuggi's Elbkate",xp:20,ll:[53.5438,9.9185],tags:["fisch"],
 why:"Övelgönne iskelesinde sıcak ringa ve somonlu basit ama sevilen Fischbrötchen.",
 tip:"Fähre 62'den inince ilk durak. Az malzeme, çok lezzet.",
 ph:["Einmal Matjes, bitte.","Bir Matjes, lütfen."]},
{id:"jenischpark",r:"elbstrand",t:"gez",n:"Jenischpark & Jenisch Haus",xp:20,ll:[53.5555,9.8595],tags:["free"],
 why:"İngiliz tarzı peyzaj parkı ve klasik villa; Elbe yürüyüşünde mola noktası.",
 tip:"Parkın içindeki Ernst Barlach Haus küçük ama güzel bir heykel müzesi.",
 ph:["Ist das ein Museum?","Burası müze mi?"]},
{id:"treppenviertel",r:"elbstrand",t:"gez",n:"Blankenese Treppenviertel",xp:30,ll:[53.5580,9.8030],tags:["free","view"],
 why:"Elbe yamacında ~5.000 basamaklık merdivenler arasında eski balıkçı ve kaptan evleri. Hamburg'un 'Akdeniz köşesi'.",
 tip:"Yorulursan 48 numaralı minibüs 'Bergziege' (dağ keçisi) dar yollardan seni yukarı çıkarır.",
 ph:["Fährt der Bus zur Bergziege hier ab?","'Bergziege' otobüsü buradan mı kalkıyor?"],film:"Merdivenlerden aşağı inerken açılan Elbe manzarası — drone gibi tek plan."},
{id:"suellberg",r:"elbstrand",t:"gez",n:"Süllberg",xp:20,ll:[53.5605,9.8045],tags:["view"],
 why:"Blankenese'nin tepesi: kuzey Almanya'nın en güzel nehir manzaralarından birinde, Michelin yıldızlı Karlheinz Hauser'in restoranı da burada.",
 tip:"Restoran yerine teraslardan manzara + kahve.",
 chef:"Yıldızlı mutfak hakkında hayal kur: Almanya'da Michelin restoranları stajyer (Praktikant) alır.",
 ph:["Kann man hier nur einen Kaffee trinken?","Burada sadece kahve içilebilir mi?"]},
{id:"willkommhoeft",r:"elbstrand",t:"yap",n:"Willkomm-Höft (Wedel)",xp:40,ll:[53.5770,9.6935],rad:800,tags:["free"],
 why:"Hamburg'a giren ve çıkan büyük gemiler burada ülkelerinin milli marşı ve bayrak selamıyla karşılanır! Türk bayraklı bir gemi yakalarsan İstiklal Marşı çalar.",
 tip:"S1 ile Wedel, sonra yürüyüş. Schulauer Fährhaus'un terasında otur.",
 ph:["Welches Schiff kommt als Nächstes?","Sıradaki gemi hangisi?"],film:"Selamlama anı + marş sesi — kesin izlenir."},
{id:"falkenstein",r:"elbstrand",t:"gez",n:"Falkenstein Kumsalı & Leuchtturm Wittenbergen",xp:20,ll:[53.5680,9.7600],rad:1200,tags:["free"],
 why:"Blankenese'nin batısında daha vahşi, sakin kumsal ve küçük bir deniz feneri.",
 tip:"Blankenese'den kumsal boyunca batıya yürü.",
 ph:["Ist das hier noch Hamburg?","Burası hâlâ Hamburg mu?"]},

/* ---------------- ALSTER, WINTERHUDE, STADTPARK ---------------- */
{id:"alsterrunde",r:"alster",t:"yap",n:"Außenalster Turu (7,4 km)",xp:30,ll:[53.5640,10.0070],rad:1500,tags:["free"],
 why:"Hamburgluların koşu ve yürüyüş rotası. Yol boyunca villalar, ABD Konsolosluğu ('Alster'deki Beyaz Saray'), yelkenliler.",
 tip:"Yürü ya da koş; StadtRAD bisikletiyle de olur. Kennedybrücke ile Krugkoppelbrücke arası en güzel kısım.",
 ph:["Ich laufe einmal um die Alster.","Alster'in etrafında bir tur koşuyorum."]},
{id:"kanu",r:"alster",t:"yap",n:"Kano ile Alster Kanalları",xp:40,ll:[53.5830,10.0170],tags:[],months:[4,5,6,7,8,9,10],
 why:"Hamburg'da Venedik ve Amsterdam'ın toplamından fazla köprü var. Winterhude ve Eppendorf'un villa bahçeli kanallarını kanoyla gez.",
 tip:"Nisan–Ekim; Osterbekkanal ve Isekanal çevresindeki kano kiralama yerlerinden saatlik kirala. Hafta içi sakin.",
 ph:["Ich möchte ein Kanu für zwei Stunden mieten.","İki saatliğine bir kano kiralamak istiyorum."],film:"Kanonun burnuna kamera — kanalda süzülme planı."},
{id:"stadtpark",r:"alster",t:"gez",n:"Stadtpark",xp:20,ll:[53.5965,10.0200],tags:["free"],
 why:"Hamburg'un 'Central Park'ı: çimler, göl, yazın açık hava konser sahnesi (Stadtpark Open Air).",
 tip:"Yazın çimlere uzan, Stadtparksee'de serinle.",
 ph:["Wollen wir zusammen grillen?","Birlikte mangal yapalım mı?"]},
{id:"planetarium",r:"alster",t:"yap",n:"Planetarium Hamburg",xp:30,ll:[53.5967,10.0085],tags:["rain","night"],
 why:"Eski bir su kulesindeki dünyanın en modern planetaryumlarından. Gösterilerin bazıları müzikli.",
 tip:"Biletleri önceden al. Altındaki 'Schmidtchen' kafede Franzbrötchen var.",
 ph:["Ist die Show auf Deutsch?","Gösteri Almanca mı?"]},
{id:"ohlsdorf",r:"alster",t:"gez",n:"Ohlsdorf Mezarlığı",xp:30,ll:[53.6225,10.0430],rad:1500,tags:["free"],
 why:"Dünyanın en büyük park mezarlıklarından (~390 hektar): içinde otobüs hatları, göller ve heykeller var. Sakin, garip derecede huzurlu.",
 tip:"Haritayı girişten al. Sessiz ve saygılı ol.",
 ph:["Wo ist der Haupteingang?","Ana giriş nerede?"]},
{id:"goldbekmarkt",r:"alster",t:"yap",n:"Goldbekmarkt (Winterhude)",xp:20,ll:[53.5855,10.0170],tags:["market"],
 why:"Kanal kenarında sevilen bir semt pazarı; Mühlenkamp çevresiyle birleştir.",
 tip:"Pazar günlerini kontrol et (genelde Salı, Perşembe, Cumartesi sabah).",
 chef:"Sezon sebzelerini öğren: Grünkohl (kara lahana, kış), Spargel (kuşkonmaz, bahar), Rote Bete, Pastinake.",
 ph:["Was ist gerade Saison?","Şu an mevsiminde olan ne?"]},
{id:"pritsch",r:"alster",t:"ye",n:"Pritsch — Franzbrötchen",xp:20,ll:[53.5660,10.0225],tags:["franz"],
 why:"1948'den beri Uhlenhorst'ta bir aile pastanesi; Franzbrötchen'leri çeşitli üst malzemelerle.",
 tip:"Alster turunun sonunda ödül olarak.",
 ph:["Haben Sie Franzbrötchen mit Streuseln?","Kırıntılı Franzbrötchen'iniz var mı?"]},
{id:"krugkoppel",r:"alster",t:"gez",n:"Krugkoppelbrücke'de Gün Batımı",xp:20,ll:[53.5755,10.0000],tags:["free","view","night"],
 why:"Alster'in kuzey ucundaki köprü: güneş göl üzerinden şehir siluetinin arkasına batar.",
 tip:"Yazın köprü kenarındaki kafelerden birinde otur.",
 ph:["Der Sonnenuntergang ist wunderschön.","Gün batımı çok güzel."],film:"Altın saat timelapse."},

/* ---------------- EIMSBÜTTEL, EPPENDORF ---------------- */
{id:"isemarkt",r:"eimsbuettel",t:"yap",n:"Isemarkt",xp:30,ll:[53.5773,9.9800],tags:["market","fisch"],
 why:"U3 viyadüğünün altında ~1 km: Avrupa'nın en uzun açık hava pazarlarından. Her Salı ve Cuma sabahı.",
 tip:"Salı/Cuma ~08:30–14:00. Balık tezgahlarından bir Fischbrötchen ile bitir.",
 chef:"Bir aşçı için en iyi okul: sezon ürünleri, peynirler, balık türlerinin Almanca isimleri. Tezgahta pazarlık değil sohbet yapılır.",
 ph:["Ich hätte gern 500 Gramm davon.","Bundan 500 gram istiyorum."],film:"Pazar boyunca yürüyüş + tezgah close-up'ları."},
{id:"kleinekonditorei",r:"eimsbuettel",t:"ye",n:"Die kleine Konditorei — Franzbrötchen",xp:20,ll:[53.5772,9.9505],tags:["franz"],
 why:"Birçok listede 'şehrin belki de en iyi Franzbrötchen'i'. Her gün taze.",
 tip:"Sabah git, öğlene doğru bitebilir.",
 ph:["Sind die Franzbrötchen von heute?","Franzbrötchen'ler bugünün mü?"]},
{id:"osterstrasse",r:"eimsbuettel",t:"ye",n:"Osterstraße — Eurovita Balık Köftesi",xp:20,ll:[53.5745,9.9530],tags:["fisch"],
 why:"Eimsbüttel'in alışveriş caddesi; Eurovita'nın her gün taze yapılan balık köfteli sandviçleri.",
 tip:"Osterstraße'de yürü, mahalle hayatını izle.",
 chef:"Fischfrikadelle tarifi: balık + bayat ekmek + soğan + hardal + dereotu. Türk balık köftesiyle kıyasla.",
 ph:["Eine Fischfrikadelle im Brötchen, bitte.","Ekmek arası bir balık köftesi, lütfen."]},
{id:"hagenbeck",r:"eimsbuettel",t:"yap",n:"Tierpark Hagenbeck",xp:40,ll:[53.5975,9.9420],tags:[],
 why:"1907'de dünyada ilk kez hayvanları kafes yerine hendekli açık alanlarda sergileyen hayvanat bahçesi. Tropik akvaryumu da var.",
 tip:"Bütün gün ayır. Akvaryum yağmurlu günde ayrı gidilebilir.",
 ph:["Wann ist die Fütterung?","Hayvanları besleme saati ne zaman?"]},
{id:"eppendorferbaum",r:"eimsbuettel",t:"gez",n:"Eppendorfer Baum & Isebekkanal",xp:20,ll:[53.5780,9.9795],tags:["free"],
 why:"Art Nouveau binalar, şık kafeler; kanal boyunca yeşil yürüyüş yolu.",
 tip:"Isemarkt'tan sonra Isebek kanalı boyunca yürü.",
 ph:["Wie heißt diese Straße?","Bu sokağın adı ne?"]},
{id:"muehlenteich",r:"eimsbuettel",t:"gez",n:"Eppendorfer Mühlenteich — Kuğu Kışlığı",xp:20,ll:[53.5935,9.9910],tags:["free"],
 why:"Alster kuğuları her kış buraya, korunaklı kışlıklarına taşınır ve baharda geri döner.",
 tip:"Kış aylarında kuğuları burada ziyaret et.",
 ph:["Hier überwintern die Alsterschwäne.","Alster kuğuları burada kışlıyor."]},

/* ---------------- ELBINSELN ---------------- */
{id:"energiebunker",r:"elbinseln",t:"gez",n:"Energiebunker Wilhelmsburg",xp:30,ll:[53.4993,9.9930],tags:["view"],
 why:"Savaştan kalma uçaksavar bunkeri, bugün güneş ve atık ısı ile mahalleyi ısıtan bir yenilenebilir enerji santrali. Tepesinde kafe ve teras.",
 tip:"Teras/kafe açılış saatleri sınırlı — gitmeden kontrol et. Manzara bütün limanı kapsıyor.",
 ph:["Ist die Terrasse heute geöffnet?","Teras bugün açık mı?"]},
{id:"ballinstadt",r:"elbinseln",t:"yap",n:"BallinStadt — Göç Müzesi",xp:30,ll:[53.5165,10.0255],tags:["rain","museum"],
 why:"1850–1939 arasında 5 milyondan fazla insan Hamburg'dan Amerika'ya göç etti; bu barakalarda bekledi. Göçmen olarak sana dokunacak bir müze.",
 tip:"Atalarını aramak için veri tabanı da var. Kendi göç hikayeni de not al.",
 ph:["Ich bin auch ein Einwanderer.","Ben de bir göçmenim."]},
{id:"veddelerfisch",r:"elbinseln",t:"ye",n:"Veddeler Fischgaststätte",xp:30,ll:[53.5208,10.0170],tags:["fisch","klasik"],
 why:"Yüz yıllık liman işçisi lokantası: çıtır kızarmış balık ve ev yapımı salatalar, turist yok.",
 tip:"Öğle vakti git; açılış saatleri sınırlı.",
 chef:"Alman 'Gaststätte' kültürü: basit, bol porsiyon, sabit menü. Kızartma tekniklerine dikkat et.",
 ph:["Was können Sie empfehlen?","Ne önerirsiniz?"]},
{id:"inselpark",r:"elbinseln",t:"gez",n:"Inselpark & Reiherstiegviertel",xp:20,ll:[53.4925,10.0060],tags:["free"],
 why:"Wilhelmsburg'un yeşil kalbi; Reiherstieg mahallesi karışık nüfusuyla 'Hamburg'un Brooklyn'i' diye anılır.",
 tip:"Bisikletle gez; Honigfabrik kültür merkezine uğra.",
 ph:["Wo kann ich hier ein Fahrrad leihen?","Burada nereden bisiklet kiralayabilirim?"]},
{id:"muehlejohanna",r:"elbinseln",t:"gez",n:"Windmühle Johanna",xp:20,ll:[53.4830,10.0310],tags:["free"],
 why:"Wilhelmsburg'daki tarihî yel değirmeni; bazı pazar günleri açılıp un öğütme gösterilir.",
 tip:"Açık günlerini kontrol et.",
 chef:"Alman un tiplerini öğren: Type 405 (pasta), 550 (ekmek), 1050, Roggen (çavdar).",
 ph:["Welches Mehl ist das?","Bu hangi un?"]},

/* ---------------- FINKENWERDER & ALTES LAND ---------------- */
{id:"scholle",r:"altesland",t:"ye",n:"Finkenwerder Scholle",xp:40,ll:[53.5345,9.8650],tags:["klasik","fisch"],pork:"Klasiği Speck (domuz pastırması) ile: 'Ohne Speck, bitte.'",
 why:"Finkenwerder balıkçı köyünün ünlü yemeği; Mayıs–Ağustos 'Maischolle' dönemi en iyisi.",
 tip:"Fähre 62 ile Finkenwerder'e git; iskele çevresindeki balık lokantalarında sor.",
 chef:"Pisi balığı tereyağında bütün kızarır; üstüne pastırma küpleri (bazen Nordseekrabben), yanında patates salatası. Pastırmasız tereyağı-karides versiyonu da harika.",
 ph:["Ist das die Finkenwerder Scholle?","Bu Finkenwerder usulü pisi mi?"]},
{id:"altesland",r:"altesland",t:"yap",n:"Altes Land Elma Bahçeleri",xp:40,ll:[53.5300,9.6880],rad:3000,tags:["free"],
 why:"Kuzey Avrupa'nın en büyük kesintisiz meyve yetiştirme bölgesi. Nisan sonu–Mayıs çiçeklenme, Ağustos–Ekim hasat.",
 tip:"Jork çevresinde bisiklet kirala; çiftlik dükkanlarında (Hofladen) elma suyu, pasta. Hasatta 'Selbstpflücke' (kendin topla) yerleri var.",
 chef:"Elma çeşitlerini tat: Elstar, Jonagold, Boskoop (pişirmeye en iyisi). Altländer usulü elmalı pasta tarifi iste.",
 ph:["Kann man hier selbst pflücken?","Burada kendimiz toplayabilir miyiz?"],film:"Çiçeklenmede bisiklet POV — pembe beyaz koridor."},
{id:"faehrecranz",r:"altesland",t:"yap",n:"Blankenese–Cranz Feribotu",xp:30,ll:[53.5390,9.7780],rad:1200,tags:["ferry","view"],
 why:"Elbe'yi Blankenese'den Altes Land'e geçen küçük feribot; liman feribotlarından çok farklı bir kırsal yolculuk.",
 tip:"Sefer saatlerini kontrol et (HVV). Cranz'dan Jork'a bisiklet ya da otobüs.",
 ph:["Wann fährt die letzte Fähre zurück?","Son dönüş feribotu ne zaman?"]},
{id:"airbus",r:"altesland",t:"gez",n:"Rüschpark & Airbus Manzarası",xp:20,ll:[53.5390,9.8560],tags:["free"],
 why:"Finkenwerder'de Airbus'ın dev uçak fabrikası var; Rüschpark'tan Elbe ve fabrika manzarası. Şanslıysan balina gibi 'Beluga' kargo uçağı.",
 tip:"Fabrika turları önceden rezervasyonla — ilgini çekerse ara.",
 ph:["Kann man hier Flugzeuge sehen?","Burada uçak görülebilir mi?"]},

/* ---------------- GÜNÜBİRLİK ---------------- */
{id:"luebeck",r:"ausflug",t:"yap",n:"Lübeck",xp:60,ll:[53.8660,10.6840],rad:3000,tags:[],
 why:"Hansa Birliği'nin 'kraliçesi': Holstentor, tuğla gotik kiliseler, UNESCO adası. Hamburg'dan bölgesel trenle ~45 dk.",
 tip:"Niederegger'de marzipan kafesi; dönüşte Travemünde'de Baltık kıyısı.",
 chef:"Lübeck marzipanı: badem oranı yüksek. Niederegger'in marzipan müzesine bak; Türk badem ezmesiyle kıyasla.",
 ph:["Ein Stück Marzipantorte, bitte.","Bir dilim marzipanlı pasta, lütfen."]},
{id:"lueneburg",r:"ausflug",t:"yap",n:"Lüneburg",xp:50,ll:[53.2490,10.4110],rad:3000,tags:[],
 why:"Tuz ticaretiyle zenginleşmiş Hansa şehri; tuz madeni yüzünden eğri duran evler. ~30 dk.",
 tip:"Am Stintmarkt'ta nehir kenarı, Tuz Müzesi (Salzmuseum).",
 chef:"Tuzun tarihi: Lüneburg tuzu ringa balığını korumak için Baltık'a taşınırdı.",
 ph:["Warum sind die Häuser so schief?","Evler neden bu kadar eğri?"]},
{id:"stade",r:"ausflug",t:"yap",n:"Stade",xp:40,ll:[53.6005,9.4765],rad:2500,tags:[],
 why:"Altes Land'in kapısında küçük Hansa şehri; Fischmarkt limanı çok fotojenik. S-Bahn ile gidilir.",
 tip:"Altes Land gezisiyle birleştirilebilir.",
 ph:["Wo ist der alte Hafen?","Eski liman nerede?"]},
{id:"cuxhaven",r:"ausflug",t:"yap",n:"Cuxhaven & Wattwanderung",xp:60,ll:[53.8690,8.7070],rad:4000,tags:[],
 why:"UNESCO Wattenmeer: gelgitte deniz çekilince deniz tabanında rehberle yürüyüş! Elbe'nin denize döküldüğü yer.",
 tip:"Watt yürüyüşü SADECE rehberle; gelgit saatleri hayati. Alte Liebe iskelesinden gemileri izle.",
 chef:"Krabbenkutter (karides tekneleri) limanda taze karides satar — kendin soy!",
 ph:["Wann ist Ebbe?","Cezir (alçak su) ne zaman?"]},
{id:"spo",r:"ausflug",t:"yap",n:"St. Peter-Ording",xp:60,ll:[54.3070,8.6400],rad:4000,tags:[],
 why:"12 km'lik dev kumsal ve kazıklar üstündeki ikonik ahşap kafeler (Pfahlbauten).",
 tip:"Rüzgarlı! Kalın giyin. Uçurtma sörfçülerini izle.",
 ph:["Ist es heute sehr windig?","Bugün çok rüzgarlı mı?"],film:"Kazıklı yapıların arasında drone-vari geniş plan."},
{id:"sylt",r:"ausflug",t:"yap",n:"Sylt",xp:80,ll:[54.9070,8.3100],rad:6000,tags:[],
 why:"Almanya'nın en kuzey adası; tren deniz üstündeki setten (Hindenburgdamm) geçerek gider. Kumullar, kırmızı falezler.",
 tip:"Deutschlandticket ile ~3 saat; erken çık. List'teki 'Gosch' Almanya'nın en kuzeydeki balık büfesi olarak bilinir.",
 chef:"Sylt istiridyesi (Sylter Royal) — List'te tat.",
 ph:["Eine Auster, bitte. Wie isst man die?","Bir istiridye, lütfen. Nasıl yeniyor?"]},
{id:"schwerin",r:"ausflug",t:"yap",n:"Schwerin Sarayı",xp:50,ll:[53.6245,11.4185],rad:2500,tags:[],
 why:"Göl üzerindeki adada masal gibi bir saray; Almanya'nın en güzel saraylarından.",
 tip:"Bölgesel trenle ~1,5 saat. Saray bahçeleri ücretsiz.",
 ph:["Wie viel kostet der Eintritt?","Giriş ne kadar?"]},
{id:"bremen",r:"ausflug",t:"yap",n:"Bremen",xp:50,ll:[53.0758,8.8072],rad:3000,tags:[],
 why:"Bremen Mızıkacıları heykeli, Schnoor mahallesi, UNESCO Rathaus ve Roland heykeli. ~1 saat.",
 tip:"Eşeğin ön ayaklarını tutup dilek dile (gelenek).",
 chef:"Kışın 'Grünkohl mit Pinkel' bölgesel klasik (domuz içerir).",
 ph:["Wo sind die Stadtmusikanten?","Mızıkacılar nerede?"]}
];

/* Etkinlikler: ranges = kesin tarihler; months = her yıl tekrar eden (tarihi kontrol et).
   Her etkinlik tamamlanınca XP verir; bölge kilidi yok — kaçırma diye. */
const EVENTS=[
 {id:"winterdom26",n:"Hamburger Winterdom",xp:40,ll:[53.5530,9.9700],ranges:[["2026-11-06","2026-12-06"]],tags:["night"],
  d:"Kuzey Almanya'nın en büyük lunaparkı, Heiligengeistfeld'de. Giriş ücretsiz; her Cuma 22:30 havai fişek. Çarşamba aile günü (indirim).",
  chef:"Dom yiyecekleri: Schmalzkuchen (pudra şekerli kızarmış hamur — Hamburg klasiği), gebrannte Mandeln, Langos, Backfisch.",
  ph:["Eine Tüte Schmalzkuchen, bitte.","Bir paket Schmalzkuchen, lütfen."]},
 {id:"fruehlingsdom27",n:"Hamburger Frühlingsdom",xp:40,ll:[53.5530,9.9700],ranges:[["2027-03-19","2027-04-18"]],tags:["night"],
  d:"Dom'un bahar versiyonu. Pzt–Per 15–23, Cuma–Cmt 15–24, Pazar 14–23.",ph:["Wann ist das Feuerwerk?","Havai fişek ne zaman?"]},
 {id:"sommerdom",n:"Hamburger Sommerdom",xp:40,ll:[53.5530,9.9700],months:[7,8],tags:["night"],
  d:"Dom'un yaz versiyonu (Temmuz sonu–Ağustos). Tarih: hamburg.de/dom.",ph:["Wie viel kostet eine Fahrt?","Bir tur kaç para?"]},
 {id:"wm-rathaus26",n:"Weihnachtsmarkt Rathausmarkt",xp:30,ll:[53.5505,9.9925],ranges:[["2026-11-23","2026-12-23"]],tags:["night"],
  d:"Belediye sarayı önündeki tarihî Noel pazarı, her gün 11–21. Uçan Noel Baba 16:00, 18:00, 20:00'de pazarın üstünden geçer.",
  chef:"Glühwein (sıcak şarap) ya da alkolsüz 'Kinderpunsch', Reibekuchen (patates mücveri) + elma püresi, Bratwurst (domuz olabilir), Lebkuchen.",
  ph:["Einen Kinderpunsch, bitte — ohne Alkohol.","Bir Kinderpunsch, lütfen — alkolsüz."]},
 {id:"santapauli26",n:"Santa Pauli",xp:30,ll:[53.5492,9.9645],ranges:[["2026-11-09","2026-12-23"]],tags:["night"],
  d:"Reeperbahn'da 'Hamburg'un en şımarık Noel pazarı', Spielbudenplatz'da. Hafta sonu gece 1'e kadar.",ph:["Frohe Weihnachten!","Mutlu Noeller!"]},
 {id:"winterpride26",n:"Winter Pride (Lange Reihe)",xp:20,ll:[53.5573,10.0148],ranges:[["2026-11-15","2026-12-21"]],tags:["night"],
  d:"St. Georg'da küçük, renkli ve rahat bir kış pazarı.",ph:["Schöne Feiertage!","İyi bayramlar/tatiller!"]},
 {id:"silvester26",n:"Silvester — Yılbaşı Havai Fişekleri",xp:30,ll:[53.5458,9.9706],ranges:[["2026-12-31","2027-01-01"]],tags:["night"],
  d:"Landungsbrücken, Alster ve Elbe kıyısında gece yarısı havai fişek. Almanlar kendi fişeklerini de patlatır — kalabalık ve gürültülü, dikkatli ol.",
  ph:["Guten Rutsch ins neue Jahr!","Yeni yıla iyi bir 'kayış'! (yılbaşı dileği)"]},
 {id:"schwaene",n:"Kuğuların Kışlığa Taşınması",xp:20,ll:[53.5530,9.9935],months:[11],tags:["free"],
  d:"Kasım'da (hava soğuyunca) Schwanenvater, Alster kuğularını teknelerle toplayıp Eppendorfer Mühlenteich'e taşır. Baharda (Mart/Nisan) geri getirir. Tarihi yerel haberlerden takip et.",
  ph:["Wann werden die Schwäne abgeholt?","Kuğular ne zaman toplanacak?"]},
 {id:"eisarena",n:"Planten un Blomen Buz Pisti",xp:20,ll:[53.5608,9.9800],months:[11,12,1,2,3],tags:[],
  d:"Kışın Avrupa'nın büyük açık hava buz pistlerinden biri. Paten kiralanabilir.",ph:["Ich brauche Schlittschuhe in Größe 43.","43 numara paten lazım."]},
 {id:"lichterfahrt",n:"Liman Işık Turu (Lichterfahrt)",xp:30,ll:[53.5455,9.9720],months:[10,11,12,1,2,3],tags:["night","view"],
  d:"Karanlık erken çöktüğü aylarda akşam Barkasse turları: aydınlatılmış Speicherstadt ve terminaller.",ph:["Wann startet die Lichterfahrt?","Işık turu ne zaman başlıyor?"]},
 {id:"gruenkohl",n:"Grünkohl Sezonu",xp:20,ll:[53.5530,10.0090],months:[11,12,1,2],tags:["klasik"],
  d:"İlk dondan sonra kara lahana tatlanır; kuzeyde kışın 'Grünkohl' yenir. Geleneksel lokantalarda dene.",
  chef:"Kara lahana saatlerce domuz yağı, soğan ve yulafla pişer; yanında Kassler, Kohlwurst, Pinkel (hepsi domuz). Kendin dana/hindi ile helal versiyon dene!",
  ph:["Gibt es den Grünkohl auch ohne Schweinefleisch?","Grünkohl domuz etsiz de var mı?"]},
 {id:"stint",n:"Stint Sezonu",xp:30,ll:[53.5208,10.0170],months:[2,3,4],tags:["fisch","klasik"],
  d:"Elbe'nin küçük balığı Stint (gümüş balığı), yumurtlamak için nehre çıkar; birkaç hafta boyunca Elbe kıyısı lokantalarında kızartılır.",
  chef:"Unlanıp tereyağında kızarır, kızarmış patates ve salata ile. Taze salatalık gibi kokar! Hamsi tavaya benzer — karşılaştır.",
  ph:["Haben Sie schon Stint?","Stint geldi mi?"]},
 {id:"spargel",n:"Spargelzeit (Kuşkonmaz)",xp:20,ll:[53.5773,9.9800],months:[4,5,6],tags:["klasik"],
  d:"Almanların takıntısı beyaz kuşkonmaz: Nisan–24 Haziran (Johannistag). Pazarlarda ve her restoranda.",
  chef:"Soyulur, tuz-şeker-tereyağlı suda pişer; Sauce Hollandaise, yeni patates ve (genelde) jambonla. Bir mutfakta çalışırsan Spargel soymayı bil!",
  ph:["Ein Kilo weißen Spargel, bitte.","Bir kilo beyaz kuşkonmaz, lütfen."]},
 {id:"bluete",n:"Altes Land Çiçeklenmesi",xp:30,ll:[53.5300,9.6880],months:[4,5],tags:["free"],
  d:"Nisan sonu–Mayıs ortası milyonlarca elma ve kiraz ağacı çiçek açar; Jork'ta çiçek festivali olur.",ph:["Die Blüte ist wunderschön.","Çiçeklenme harika."]},
 {id:"hafengeburtstag27",n:"Hafengeburtstag (Liman Doğum Günü)",xp:50,ll:[53.5458,9.9706],ranges:[["2027-05-06","2027-05-09"]],tags:["free","view"],
  d:"Dünyanın en büyük liman festivali (838.). 6 Mayıs 16:00 giriş geçidi, 8 Mayıs 15:15 römorkör balesi ve 22:30 havai fişek, 9 Mayıs 17:00 çıkış geçidi.",
  ph:["Wo sieht man die Einlaufparade am besten?","Giriş geçidini en iyi nereden görürüm?"]},
 {id:"kirschbluete",n:"Kirschblütenfest — Alster Havai Fişeği",xp:30,ll:[53.5640,10.0070],months:[5],tags:["free","night"],
  d:"Hamburg'daki Japon topluluğunun teşekkürü olarak Alster üzerinde büyük havai fişek. Mayıs'ta bir cuma; tarihi kontrol et.",ph:["Wann ist das Feuerwerk an der Alster?","Alster'deki havai fişek ne zaman?"]},
 {id:"matjes",n:"Yeni Matjes Sezonu",xp:20,ll:[53.5453,9.9683],months:[6],tags:["fisch"],
  d:"Haziran'da yeni sezonun genç ringaları (Matjes) gelir; balık büfelerinde 'Neuer Matjes' tabelalarına bak.",
  chef:"Matjes: yumurtlamamış genç ringa, hafif tuzda olgunlaştırılır. Hausfrauenart sosu: elma, soğan, ekşi krema, turşu.",
  ph:["Ist das schon der neue Matjes?","Bu yeni Matjes mi?"]},
 {id:"rotegruetze",n:"Rote Grütze Mevsimi",xp:20,ll:[53.5491,9.9772],months:[6,7,8],tags:["klasik"],
  d:"Yaz meyveli kuzey tatlısı; vanilyalı sos ya da kremayla.",
  chef:"Kırmızı meyveler (frenk üzümü, ahududu, kiraz) + şeker + nişasta; muhallebi mantığı. Mutfakta kolay ve etkileyici.",
  ph:["Rote Grütze mit Vanillesoße, bitte.","Vanilya soslu Rote Grütze, lütfen."]},
 {id:"birnenbohnen",n:"Birnen, Bohnen und Speck Sezonu",xp:20,ll:[53.5532,10.0092],months:[8,9],tags:["klasik"],
  d:"Yaz sonu Hamburg klasiği; geleneksel lokantaların menüsüne girer (domuz pastırması içerir).",
  ph:["Ist das ein typisches Hamburger Gericht?","Bu tipik bir Hamburg yemeği mi?"]},
 {id:"harleydays",n:"Harley Days",xp:20,ll:[53.5640,9.9850],months:[6,7],tags:["free"],
  d:"Binlerce Harley-Davidson şehirde geçit yapar. Tarih yıla göre değişir — kontrol et.",ph:["Was für ein Motorrad!","Ne motor ama!"]},
 {id:"pride",n:"Hamburg Pride / CSD",xp:20,ll:[53.5520,9.9922],months:[8],tags:["free"],
  d:"Ağustos'ta büyük yürüyüş ve Jungfernstieg'de sokak festivali.",ph:["Wo geht die Parade lang?","Geçit nereden geçiyor?"]},
 {id:"reeperbahnfestival",n:"Reeperbahn Festival",xp:30,ll:[53.5495,9.9625],months:[9],tags:["night"],
  d:"Eylül'de St. Pauli kulüplerinde yüzlerce yeni grup; Avrupa'nın büyük kulüp festivallerinden. Bazı açık hava sahneleri ücretsiz.",ph:["Wer spielt heute im Club?","Bugün kulüpte kim çalıyor?"]},
 {id:"filmfest",n:"Filmfest Hamburg",xp:20,ll:[53.5560,9.9890],months:[9,10],tags:["rain","night"],
  d:"Eylül sonu–Ekim başı film festivali. Video çeken biri için söyleşiler ilham verici.",ph:["Hat der Film Untertitel?","Filmin altyazısı var mı?"]},
 {id:"marathon",n:"Haspa Marathon Hamburg",xp:20,ll:[53.5600,9.9750],months:[4],tags:["free"],
  d:"Nisan'da şehrin içinden koşu; koşmasan da kenarda tezahürat yap.",ph:["Weiter so! Ihr schafft das!","Devam! Başaracaksınız!"]},
 {id:"kielerwoche",n:"Kieler Woche (Kiel)",xp:40,ll:[54.3233,10.1394],months:[6],tags:["free"],rad:4000,
  d:"Haziran'ın son haftası dünyanın en büyük yelken festivali; Deutschlandticket ile Kiel ~1,5 saat.",ph:["Wo fährt der Zug nach Kiel?","Kiel treni nereden kalkıyor?"]},
 {id:"fussball",n:"Stadyumda Maç (HSV ya da St. Pauli)",xp:40,ll:[53.5872,9.8986],months:[8,9,10,11,12,1,2,3,4,5],tags:["night"],
  d:"Şehrin iki kulübü: HSV (Volksparkstadion) ve FC St. Pauli (Millerntor). Fikstür ve bilet durumuna bak.",ph:["Gibt es noch Tickets für das Spiel?","Maç için hâlâ bilet var mı?"]}
];

/* Seviyeler: Quiddje = Hamburg'da doğmamış Hamburglu (şaka yollu). */
const LEVELS=[
 {xp:0,n:"Tourist",tr:"Turist"},
 {xp:100,n:"Neuankömmling",tr:"Yeni gelen"},
 {xp:250,n:"Quiddje",tr:"Dışarıdan gelen Hamburglu"},
 {xp:450,n:"Kiez-Kenner",tr:"Mahalleyi bilen"},
 {xp:700,n:"Hamburger Jung",tr:"Hamburg delikanlısı"},
 {xp:1000,n:"Hanseat",tr:"Hansalı"},
 {xp:1400,n:"Elbkapitän",tr:"Elbe kaptanı"},
 {xp:1900,n:"Hamburger Original",tr:"Hamburg'un simgesi"},
 {xp:2600,n:"Ehrenbürger",tr:"Fahri hemşehri"}
];

/* Rozetler: test(stats) → [mevcut, hedef] */
const BADGES=[
 {id:"fisch",n:"Fischbrötchen Avcısı",d:"5 farklı balık durağı",ic:"🐟",tag:"fisch",goal:5},
 {id:"franz",n:"Franzbrötchen Jürisi",d:"4 farklı yerde Franzbrötchen",ic:"🥐",tag:"franz",goal:4},
 {id:"klasik",n:"Hanse Mutfağı",d:"6 klasik Hamburg yemeği",ic:"🍲",tag:"klasik",goal:6},
 {id:"view",n:"Yükseklik Korkusu Yok",d:"6 manzara noktası",ic:"🗼",tag:"view",goal:6},
 {id:"ferry",n:"Su Yolcusu",d:"4 tekne/feribot yolculuğu",ic:"⛴️",tag:"ferry",goal:4},
 {id:"market",n:"Pazar Çocuğu",d:"4 pazar",ic:"🧺",tag:"market",goal:4},
 {id:"museum",n:"Müze Faresi",d:"6 müze",ic:"🏛️",tag:"museum",goal:6},
 {id:"night",n:"Gece Kuşu",d:"6 akşam/gece görevi",ic:"🌙",tag:"night",goal:6},
 {id:"free",n:"Bedavacı",d:"15 ücretsiz keşif",ic:"🆓",tag:"free",goal:15},
 {id:"chef",n:"Şefin Defteri",d:"10 aşçı notlu görev",ic:"👨‍🍳",special:"chef",goal:10},
 {id:"events",n:"Mevsimlik",d:"5 etkinlik",ic:"🎡",special:"events",goal:5},
 {id:"gps",n:"Gerçek Kaşif",d:"15 konumla doğrulanmış görev",ic:"📍",special:"gps",goal:15},
 {id:"vlog",n:"Vlogger",d:"15 görevi videoya çek",ic:"🎥",special:"vlog",goal:15},
 {id:"words",n:"Moin Ustası",d:"30 Almanca cümle topla",ic:"🗣️",special:"words",goal:30},
 {id:"region",n:"Bölge Fatihi",d:"Bir bölgeyi %100 bitir",ic:"🏁",special:"region",goal:1},
 {id:"streak",n:"Düzenli Kaşif",d:"4 hafta üst üste keşif",ic:"🔥",special:"streak",goal:4},
 {id:"trips",n:"Deutschlandticket Ustası",d:"3 günübirlik gezi",ic:"🚆",special:"trips",goal:3},
 {id:"all",n:"Hamburg'u Fethettim",d:"Tüm bölgeleri aç",ic:"👑",special:"allregions",goal:13}
];
